site_name: confrm.io

repo_url: https://github.com/confrm

copyright: Copyright &copy; 2021 confrm.io

theme:
  name: material
  favicon: assets/logo.svg
  logo: assets/logo.svg
  palette:
    primary: blue grey

nav:
  - Home: index.md
  - Quickstart: 
    - quickstart/quickstart-confrm.md
    - quickstart/quickstart-rpi.md
    - quickstart/quickstart-client.md

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
